name: Infrastructure Deployment

on:
  # Triggered only with these two scenarios
  push:
    branches: [ main ]
    paths: [ 'infra/**' ]   # Targeting changes in infra/ directory
  pull_request:
    branches: [ main ]
    paths: [ 'infra/**' ]

concurrency:
  group: terraform-${{ github.ref }} # Group concurrent runs (github.ref is branch or PR identifier) to prevent multiple Terraform runs on same branch/PR
  cancel-in-progress: false # Prevents stalled runs from being cancelled.

permissions:
  contents: read  # Allows runner to download codes from the repository to build the Dockerfile, but not modify any code.
  pull-requests: write  # Allows GitHub Actions to post comments on PRs (e.g., Terraform plan output) and update PR status.

jobs:
  terraform:
    name: 'Terraform Automation'
    runs-on: ubuntu-latest  # Ephemeral GitHub-hosted runner (containerised VM)
    
    defaults:
      run:
        working-directory: ./infra  # All commands run in infra/ directory

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_gemma_api_key: ${{ secrets.GEMMA_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RG }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_SA }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      # Comparison: State file (gets current infra state) and compares against .tf files
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply
        # Apply changes only for main branch merge (push)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan